import {Dimensions, Platform, StyleSheet} from 'react-native';

export const {width} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#120458',
  },
  mainWrapper: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  logoSection: {
    alignItems: 'center',
    marginBottom: 30,
  },
  pixelLogo: {
    fontSize: 40,
    fontWeight: '900',
    color: '#FF0055',
    textShadowColor: '#00FFFF',
    textShadowOffset: {width: 2, height: 2},
    textShadowRadius: 0,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: -1,
  },
  pixelLogoVS: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFD700',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginVertical: 2,
  },
  pixelSub: {
    color: '#00FFFF',
    fontSize: 14,
    marginTop: 6,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 2,
    fontWeight: 'bold',
  },
  statusBar: {
    borderWidth: 2,
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 8,
    alignItems: 'center',
    marginBottom: 20,
    borderColor: '#555',
  },
  statusText: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  hint: {
    fontSize: 10,
    color: '#666',
    marginBottom: 4,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    // 좌/우 카드 세로높이를 동일하게 맞춤
    height: 180,
  },
  lobbyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#000',
    padding: 12,
    borderBottomWidth: 4,
    borderBottomColor: '#FF0055',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRight: {
    flexDirection: 'row',
  },
  pixelLabel: {
    color: '#FF0055',
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginRight: 6,
    fontSize: 14,
  },
  pixelValue: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 1,
  },
  mainContent: {
    flex: 1,
    padding: 12,
  },
  panelBox: {
    borderWidth: 2,
    borderColor: '#000',
    backgroundColor: '#FFF',
    marginBottom: 10,
    borderBottomWidth: 4,
    borderRightWidth: 4,
  },
  panelTitleBox: {
    backgroundColor: '#FFD700',
    padding: 6,
    borderBottomWidth: 2,
    borderBottomColor: '#000',
  },
  panelTitle: {
    fontWeight: 'bold',
    fontSize: 12,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: '#000',
    textAlign: 'center',
    letterSpacing: 1,
  },
  gridContainer: {
    padding: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    backgroundColor: '#E0E0E0',
  },
  playerSlot: {
    width: '48%',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#000',
    padding: 6,
    marginBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 2,
    borderRightWidth: 2,
    height: 40,
  },
  playerSlotMe: {
    backgroundColor: '#FFFACD',
    borderColor: '#FF0055',
  },
  avatar: {
    width: 20,
    height: 20,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
    borderWidth: 1,
    borderColor: '#555',
  },
  avatarText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 10,
  },
  slotName: {
    flex: 1,
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: '#000',
  },
  hostBadge: {
    fontSize: 8,
    fontWeight: 'bold',
    backgroundColor: '#FF0055',
    color: '#FFF',
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: '#000',
  },
  teamBadgePolice: {
    fontSize: 8,
    fontWeight: 'bold',
    backgroundColor: '#00AAFF',
    color: '#000',
    paddingHorizontal: 3,
    paddingVertical: 1,
    marginRight: 2,
    borderWidth: 1,
    borderColor: '#000',
  },
  teamBadgeThief: {
    fontSize: 8,
    fontWeight: 'bold',
    backgroundColor: '#F9F871',
    color: '#000',
    paddingHorizontal: 3,
    paddingVertical: 1,
    marginRight: 2,
    borderWidth: 1,
    borderColor: '#000',
  },
  terminalScroll: {
    flex: 1,
    backgroundColor: '#000',
  },
  terminalText: {
    color: '#00FF00',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 10,
    marginBottom: 2,
  },
  terminalTextMe: {
    color: '#00E5FF',
  },
  terminalName: {
    color: '#FF00FF',
  },
  terminalNameMe: {
    color: '#F9F871',
  },
  terminalInputRow: {
    flexDirection: 'row',
    backgroundColor: '#111',
    borderTopWidth: 2,
    borderTopColor: '#333',
    alignItems: 'center',
    padding: 4,
  },
  prompt: {
    color: '#00FF00',
    fontSize: 14,
    fontWeight: 'bold',
    marginHorizontal: 6,
  },
  terminalInput: {
    flex: 1,
    color: '#00FF00',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 12,
    height: 30,
    fontWeight: 'bold',
    paddingVertical: 0,
  },
  sendBtn: {
    backgroundColor: '#003300',
    borderWidth: 1,
    borderColor: '#00FF00',
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 2,
    borderBottomWidth: 2,
    borderRightWidth: 2,
  },
  sendBtnText: {
    color: '#00FF00',
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  footerBar: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#111',
    borderTopWidth: 4,
    borderTopColor: '#FF0055',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 20,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pixelModal: {
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#000',
    width: width * 0.85,
    shadowColor: '#000',
    shadowOffset: {width: 4, height: 4},
    shadowOpacity: 1,
    shadowRadius: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
  },
  modalHeader: {
    backgroundColor: '#000',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  modalTitle: {
    color: '#FFF',
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 16,
  },
  modalClose: {
    color: '#FF0055',
    fontWeight: 'bold',
    fontSize: 18,
  },
  qrBody: {
    padding: 20,
    alignItems: 'center',
  },
  qrCodeText: {
    marginTop: 10,
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    letterSpacing: 2,
  },
  modalText: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: '#000',
    textAlign: 'center',
  },
});

